name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build motion-poll
      run: go build -v ./cmd/motion-poll/motion-poll.go
    - name: Build set-time
      run: go build -v ./cmd/set-time/set-time.go
